# syntax=docker/dockerfile:1
FROM mcr.Microsoft.com/dotnet/sdk:6.0 As build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c release -o out

FROM mcr.Microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "platformService.dll" ]